name: InfiniCake
version: 1.2
main: me.avixk.InfiniCake.Main
api-version: 1.16
description: Adds infinite cakes
authors: [avixk]
commands:
  infinicake:
    description: Gives you an infinicake!
permissions:
  infinicake.admin:
    default: op